# This file configures the Ansible AWS EC2 dynamic inventory plugin.
plugin: aws_ec2
regions:
  - ap-south-1
filters:
  # Find instances with the 'Project' tag set by Terraform
  tag:Project: my-web-app
  # Only target instances that are currently running
  instance-state-name: running