
name: Terraform - EC2

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply changes (true) or plan only (false)"
        required: true
        type: boolean
        default: false
      destroy:
        description: "destroy changes for next run"
        required: true
        type: boolean
        default: false

# Expose secrets and pass them to Terraform as TF_VARs
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-south-1
  TF_VAR_aws_region: ap-south-1
  TF_VAR_key_name: my-test-key
  TF_VAR_allowed_ssh_cidr: ${{ secrets.ALLOWED_SSH_CIDR }}
  TF_VAR_instance_type: t3.micro
  TF_STATE_BUCKET: "test-project-terraform-my-test-new" 
  TF_STATE_DYNAMODB_TABLE: "terraform-state-lock"

jobs:
  
  bootstrap-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Bootstrap S3 Bucket for Terraform State
        run: |
          if aws s3api head-bucket --bucket "${{ env.TF_STATE_BUCKET }}" 2>/dev/null; then
            echo "S3 bucket ${{ env.TF_STATE_BUCKET }} already exists."
          else
            echo "Creating S3 bucket ${{ env.TF_STATE_BUCKET }}."
            aws s3api create-bucket \
              --bucket "${{ env.TF_STATE_BUCKET }}" \
              --region "${{ env.AWS_REGION }}" \
              --create-bucket-configuration LocationConstraint=${{ env.AWS_REGION }}
          fi
          echo "Enabling versioning on S3 bucket."
          aws s3api put-bucket-versioning --bucket "${{ env.TF_STATE_BUCKET }}" --versioning-configuration Status=Enabled
          echo "Enabling server-side encryption on S3 bucket."
          aws s3api put-bucket-encryption --bucket "${{ env.TF_STATE_BUCKET }}" --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'

      - name: Bootstrap DynamoDB Table for Terraform State Locking
        run: |
          if aws dynamodb describe-table --table-name "${{ env.TF_STATE_DYNAMODB_TABLE }}" 2>/dev/null; then
            echo "DynamoDB table ${{ env.TF_STATE_DYNAMODB_TABLE }} already exists."
          else
            echo "Creating DynamoDB table ${{ env.TF_STATE_DYNAMODB_TABLE }}."
            aws dynamodb create-table \
              --table-name "${{ env.TF_STATE_DYNAMODB_TABLE }}" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST \
              --region "${{ env.AWS_REGION }}"
            echo "Waiting for DynamoDB table to be created..."
            aws dynamodb wait table-exists --table-name "${{ env.TF_STATE_DYNAMODB_TABLE }}"
          fi

  terraform:
    needs: bootstrap-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="key=ec2-instance/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"\
            -backend-config="dynamodb_table=${{ env.TF_STATE_DYNAMODB_TABLE }}"

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        if: ${{ !inputs.destroy }}
        working-directory: ./terraform
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: ${{ inputs.apply && !inputs.destroy }}
        working-directory: ./terraform
        run: terraform apply -input=false -auto-approve tfplan

      - name: Terraform Destroy
        if: ${{ inputs.destroy }}
        working-directory: ./terraform
        run: terraform destroy -auto-approve

      - name: Show Outputs on Apply
        if: ${{ inputs.apply && !inputs.destroy }}
        working-directory: ./terraform
        run: |
          echo "### Terraform Outputs" >> $GITHUB_STEP_SUMMARY
          terraform output >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "To SSH: ssh -i /path/to/your.pem ec2-user@$(terraform output -raw public_ip)" >> $GITHUB_STEP_SUMMARY